### ISSUE TITLE
有api调用的示范的例子说明吗？

### ISSUE THREAD

**Issue by xinjiayu** [HaoyuHu/gosimhash-doc-server#1] opened 2017-11-28 01:23 UTC
按readme中说的，对identify接口提交数据，，同一个数据，不停的提交结果不一样。有的时候是
{
    "code": 0,
    "err_message": "ok",
    "data": {
        "has_similar_doc": false
    }

并且是N次都是这样，然后会有一次：
{
    "code": 0,
    "err_message": "ok",
    "data": {
        "has_similar_doc": true,
        "similar_doc_id": "22331122"
    }
}

迷糊了，请帮忙看看。

**Comment by haoyuhu** [comment] 2019-03-31 03:31
> 按readme中说的，对identify接口提交数据，，同一个数据，不停的提交结果不一样。有的时候是
> {
> "code": 0,
> "err_message": "ok",
> "data": {
> "has_similar_doc": false
> }
> 
> 并且是N次都是这样，然后会有一次：
> {
> "code": 0,
> "err_message": "ok",
> "data": {
> "has_similar_doc": true,
> "similar_doc_id": "22331122"
> }
> }
> 
> 迷糊了，请帮忙看看。

Hi, what's your post data here? the second response should be `has_similar_doc=true`, could you please talk about how to reproduce the bug?

**Comment by haoyuhu** [comment] 2019-04-18 06:49
Closing the issue since this is not likely a bug after testing. Feel free to reopen if the issue still persists.

**Closed as completed by haoyuhu** 2019-04-18 06:49 UTC
